# Generated by Django 4.1.4 on 2023-03-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
