# Generated by Django 4.1.4 on 2023-02-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_company_userrole_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobile_num',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
