# Generated by Django 4.1.4 on 2023-03-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='active_tf',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
