# Generated by Django 4.1.4 on 2023-03-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_user_created_at_user_is_active_user_updated_at'),
        ('projectApp', '0003_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.user'),
        ),
    ]
