# Generated by Django 4.1.4 on 2023-03-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteApp', '0002_alter_note_responded_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
